### ISSUE TITLE
Run a smoke test against a local Gradle build

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-aot-smoke-tests#1]
Running a smoke test against local change is quite helpful to validate that a feature hasn't broken something (or a broken test now passes).

If the local change is built against Gradle, we could point to the directory of the project. For Maven, an option to add `mavenLocal()` would be nice.

**Comment by wilkinsona** [comment]
After [a fix in Boot](https://github.com/spring-projects/spring-boot/issues/31803), this should now work properly in the Gradle case. You can do something like this `./gradlew command-line-runner:build --include-build ../spring-boot/main` to build and run the sample against the `main` worktree of your Spring Boot clone. You can specify `include-build` multiple times if you need to build against local builds of multiple Gradle-based projects.

**Comment by wilkinsona** [comment]
Gradle doesn't know anything about Git or its branches. You'd need to have your GH-2359 branch checked out somewhere and then point Gradle at that directory.

**Comment by garyrussell** [comment]
Yes, this worked...

```
% ./gradlew :spring-kafka-avro:build --include-build ../spring-kafka        
```
... with the active branch on that project

But I had to temporarily remove the `spring-kafka` smoke test

```
* What went wrong:
Included build in /Users/grussell/Development/spring-kafka has name 'spring-kafka' which is the same as a project of the main build.
```

Your reference to `/main` was the confusing part.

**Comment by wilkinsona** [comment]
Ah, sorry for the confusion. Stephane and I both use [git work trees](https://git-scm.com/docs/git-worktree) so we have multiple branches checked out at the same time. I have `spring-boot/main`, `spring-boot/2.7.x`, and `spring-boot/2.6.x` directories. I then have 3 separate Eclipse workspaces, one for each check out. It saves time with IDE refreshes when I want to change branch.

**Comment by garyrussell** [comment]
Nice!

**Comment by garyrussell** [comment]
I think this can be closed. @snicoll ?

**Comment by mhalbritter** [comment]
We now have an option for Gradle based builds, but none for Maven.

**Comment by snicoll** [comment]
It would be nice but I am not feeling strongly about it. @wilkinsona feel free to close this one if you want to restrict this to Gradle-based build.

**Comment by wilkinsona** [comment]
Let's use this for the Gradle side of things. If the requirement comes up with Maven, I can take another look.
