### ISSUE TITLE
Remove --enable-http from samples

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-aot-smoke-tests#118]
Now that https://github.com/spring-projects/spring-framework/issues/29185 is completed, we should remove the explicit addition of those properties in `build.gradle`.

https://github.com/spring-projects/spring-aot-smoke-tests/blob/d866ecc679df34788007270efb193d57d25f15d9/security-oauth2-resource-server/build.gradle#L25-L31

https://github.com/spring-projects/spring-aot-smoke-tests/blob/d866ecc679df34788007270efb193d57d25f15d9/security-oauth2-authorization-server/build.gradle#L24-L30

**Comment by wilkinsona** [comment]
Thanks, @marcusdacoregio. I've placed this on hold for now. We need to wait until the smoke tests are using Framework snapshots.
