### ISSUE TITLE
Add coverage for testing in a native image

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-aot-smoke-tests#121]
Currently, all of the smoke tests run the tests on the JVM against an app running as a separate process (on the JVM using `java -jar` or as a native image). We should add something that exercises `nativeTest` with various things (slices, `@SpringBootTest` with a mock environment, `@SpringBootTest` with a web server, etc).

**Comment by wilkinsona** [comment]
This would have caught https://github.com/spring-projects/spring-boot/issues/32848.

**Comment by mhalbritter** [comment]
I pushed a change which executes the unit tests on the JVM and in a native image. The `nativeAotTests` task now depends on `nativeTest`. I removed the useless unit tests from most of the smoke tests.

The native unit tests can be seen for example in the `command-line-runner` smoke test.

**Comment by wilkinsona** [comment]
I'd like to revisit this as I think it's resulted in individual smoke tests covering too many things. It feels like we might need two separate kinds of smoke test:

1. An app smoke test that runs an AOT-processed app on the JVM or in a native image and tests it
2. A test smoke test that runs AOT-processed tests on the JVM or in a native image
