### ISSUE TITLE
java.nio.charset problem 

### ISSUE THREAD

**Issue by JiangYanLin** [spring-projects/spring-aot-smoke-tests#147]
```java
Charset.availableCharsets().forEach((name, charset) -> {
            System.out.println(name);
});
```
The Code Above will get two differet result when runing in jvm and native.
the result in jvm has more charsets than in native.

**Comment by JiangYanLin** [comment]
this problem makes poi can not creat new workbook

**Comment by wilkinsona** [comment]
This repository is for tests that verify GraalVM native compatibility of various components in the Spring ecosystem. Unfortunately, its not the right place to report general GraalVM problems or problems with getting a library such as POI to work with GraalVM.

By default, a native image built with GraalVM does not include all charsets. You can include all of them by building your image with `-H:+AddAllCharsets` as described [here](https://medium.com/graalvm/graalvm-native-image-quick-reference-4ceb84560fd8).
