### ISSUE TITLE
Don't depend on processAot on checkFormat gradle tasks

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-aot-smoke-tests#155]
When running `gradle format` or `gradle checkFormat` on root level, this executes `processAot` in all projects. I don't think this should be necessary.

**Comment by wilkinsona** [comment]
That's annoying. The `checkFormatAot` and `checkFormatAotTest` tasks are disabled but it looks like Gradle runs all of their dependencies anyway.

**Comment by mhalbritter** [comment]
Thanks Andy!
