### ISSUE TITLE
Add a smoke test for ServletComponentScan with WebServlet, WebFilter, and WebListener

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-aot-smoke-tests#182]

**Comment by mhalbritter** [comment]
The smoke test currently fails, as the `@WebListener` annotated class is not registered automatically for reflection. I'll create an issue on the Boot tracker for it.

**Comment by mhalbritter** [comment]
Here's the issue on the Boot tracker: https://github.com/spring-projects/spring-boot/issues/36008
