### ISSUE TITLE
Investigate using mccutchen/go-httpbin

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-aot-smoke-tests#184]
I think we should take another look at the changes made for https://github.com/spring-projects/spring-aot-smoke-tests/issues/180. It may be possible to revert much of them and use `mccutchen/go-httpbin` running in a container in place of http(s)://httpbin.org.

**Comment by wilkinsona** [comment]
https://hub.docker.com/r/kennethreitz/httpbin is another option. It's the "original" implementation and is what's running at https://httpbin.org.

**Comment by mhalbritter** [comment]
I found https://hub.docker.com/r/kennethreitz/httpbin while looking for a suitable docker replacement. The problem with it is that it doesn't support ARM machines. I'm in favor of the Go re-implementation.

**Comment by wilkinsona** [comment]
Thanks, Moritz. I hadn't released that httpbin was x64 only. Let's use go-httpbin then.

**Comment by wilkinsona** [comment]
I think this has broken the tests for HTTPs. For example `rest-template` started to fail with https://github.com/spring-projects/spring-aot-smoke-tests/commit/bc7195d00d00bbd76c6dd5f4e966f39b851f05c5. See  https://ci.spring.io/teams/spring-aot-smoke-tests/pipelines/spring-aot-smoke-tests-3.0.x/jobs/rest-template-app-test/builds/81.

**Comment by mhalbritter** [comment]
Oh :( I'm going to take a look.

**Comment by mhalbritter** [comment]
We're using an old docker compose version which doesn't support the `config` element in the compose file. #187 updates docker compose to a newer version.

**Comment by mhalbritter** [comment]
And i botched the regex. It worked on my machine because it was `localhost`, but on the CI it's an IP address and `\w+` doesn't matches IP addresses.

**Comment by wilkinsona** [comment]
Thanks, @mhalbritter.
