### ISSUE TITLE
Add smoke test to validate scoped proxy use case

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-aot-smoke-tests#215]
The use case that's exposed in https://github.com/spring-projects/spring-framework/issues/32669 is quite hard to replicate in a simple test so we'll add a smoke test for it.

**Comment by wilkinsona** [comment]
They workflows have been [synced and updated](https://github.com/spring-projects/spring-aot-smoke-tests#updating-the-workflows) in 75d35cf1.
