### ISSUE TITLE
Add the use of <include> to Logback smoke test

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-aot-smoke-tests#226]

**Comment by izeye** [comment]
9c82346 seems to have intended to close this issue but didn't work for some reason.

**Comment by wilkinsona** [comment]
Thanks, @izeye. It didn't auto-close because of this repositories unusual branch structure. That means the change was never merged forwards into the default branch which is what has to happen for GitHub to do the auto-close.
