### ISSUE TITLE
nativeAppComposeDown Task Not Invoked After Test Fails

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-aot-smoke-tests#6]
...have to stop the containers manually.

**Comment by wilkinsona** [comment]
It's configured as a finaliser for the task that stops the app so it should have run. [This build scan](https://ge.spring.io/s/2wxn6z4nabt6s/timeline?details=zvy4hund32ols&show=Successors) shows that the finaliser configuration is correctly, but the task is grayed out and hasn't run. Gradle bug? I don't know what being grayed out signifies.

**Comment by wilkinsona** [comment]
I think this should be fixed now. Adding a deliberate failure to the `spring-amqp-rabbit` sample showed compose down running after a test failure: https://ge.spring.io/s/pbbj3bk5hvg3a/timeline
