### ISSUE TITLE
Upgrade to GraalVM 22.2

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-aot-smoke-tests#80]
SDKman now has support for 22.2, and Liberika Nik, which we use on CI, is now on 22.2 too: https://bell-sw.com/pages/downloads/native-image-kit/#/java-17.0.4-nik-22.2.0

**Comment by wilkinsona** [comment]
@mhalbritter,  could you please update the `.sdkmanrc` file as well?

**Comment by mhalbritter** [comment]
Ugh:

```
╰─$ sdk list java | grep nik
 Liberica NIK  |     | 22.1.r17     | nik     |            | 22.1.r17-nik        
               |     | 22.1.r11     | nik     |            | 22.1.r11-nik        
               |     | 22.0.0.2.r17 | nik     |            | 22.0.0.2.r17-nik    
               |     | 22.0.0.2.r11 | nik     |            | 22.0.0.2.r11-nik    
               |     | 21.3.2.r17   | nik     |            | 21.3.2.r17-nik      
               |     | 21.3.2.r11   | nik     |            | 21.3.2.r11-nik      
               |     | 21.2         | nik     |            | 21.2-nik            
               |     | 21.1         | nik     |            | 21.1-nik            
               |     | 21.0.0.2.r11 | nik     |            | 21.0.0.2.r11-nik    
               |     | 21.0.0.2     | nik     |            | 21.0.0.2-nik    
```

There's no `22.2` from Liberica available on my machine. Not sure if this is related to Linux/aarch64. Is this the same on your machine, too?

**Comment by wilkinsona** [comment]
Sorry, I read too much into "SDKman now has support for 22.2". I realise now that you were referring to `22.2.r17-grl`. There's no Liberia NIK `22.2` listed on my machine either.

**Comment by mhalbritter** [comment]
Ah, maybe I should start using the Liberica distribution to prevent such confusion. I'll revert CI to use 22.1 to prevent confusions that builds work on CI but fail local. When 22.2 from liberica is on SDKman, then i'll update the file.
